import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/sonner"
import Navbar from "./_components/navbar"

import { ClerkProvider } from "@clerk/nextjs"
import { ClientPostHogProvider } from "./_providers/analytics"
import { NextThemeProvider } from "./_providers/next-theme"
import { ReactQueryProvider } from "./_providers/react-query"

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <ClientPostHogProvider>
          <body
            className={cn(
              "min-h-screen bg-background font-sans antialiased",
              fontSans.variable
            )}
          >
            <NextThemeProvider>
              <ReactQueryProvider>
                <Navbar />
                {children}
                <Toaster />
              </ReactQueryProvider>
            </NextThemeProvider>
          </body>
        </ClientPostHogProvider>
      </html>
    </ClerkProvider>
  )
}
